#!/usr/bin/env python3
"""The two SDKs compose identical envelopes, and both satisfy the published schema.

This exists because the checks that were supposed to guarantee it did not.

`test-vectors.json` proves an SDK can *re-sign a body someone else composed*.
It says nothing about the body an SDK composes on its own. The test named "the
two SDKs compose identical envelopes" asserted a rule about ONE SDK's output for
ONE event kind (`tool_call`), so three real divergences lived in `main` while it
passed:

  * Python emitted `result.latency_ms: null` on decision, checkpoint and
    model-response events; TypeScript omitted the key. Different signed bytes
    for logically identical events — the exact failure [TAP-EVT-OMIT] exists to
    prevent, and the exact one the old test's own header describes.
  * Python's `record_output` used `tool: "agent.run"`; TypeScript's used
    `"agent.record"`.
  * Both emitted `action.kind: "model_response"`, which is neither one of §6.2's
    seven registered kinds nor an `x-` namespaced extension.

Every one of those was visible in `schemas/event.schema.json` — nothing had ever
validated SDK-composed events against it. `scripts/check-schemas.py` validates
the *vectors*, which are generated by `tap_ref.py`, not by either SDK.

So this does the two things neither check did:

  1. runs each SDK's own emit path over the same four event kinds and diffs the
     normalized envelope shapes;
  2. validates the raw events from BOTH against `schemas/event.schema.json`.

    python3 scripts/check-envelope-parity.py
"""
from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]


def run(label: str, cmd: list[str], cwd: Path, env: dict | None = None) -> dict:
    import os
    full_env = {**os.environ, **(env or {})}
    proc = subprocess.run(cmd, cwd=cwd, capture_output=True, text=True, env=full_env)
    if proc.returncode != 0:
        print(f"FAIL: {label} emitter exited {proc.returncode}")
        print(proc.stderr[-2000:])
        sys.exit(1)
    try:
        return json.loads(proc.stdout)
    except json.JSONDecodeError as exc:
        print(f"FAIL: {label} emitter did not produce JSON: {exc}")
        print(proc.stdout[-2000:])
        sys.exit(1)


def main() -> int:
    py = run("python", [sys.executable, "tests/emit_shapes.py"],
             REPO / "sdk" / "python", {"PYTHONPATH": "src"})
    ts = run("typescript", ["npx", "tsx", "test/emitShapes.ts"], REPO / "sdk" / "js")

    failures = 0

    # 1. Same kinds, same shapes.
    if set(py) != set(ts):
        print("FAIL: the SDKs emit different action kinds")
        print(f"  python only:     {sorted(set(py) - set(ts))}")
        print(f"  typescript only: {sorted(set(ts) - set(py))}")
        failures += 1

    for kind in sorted(set(py) & set(ts)):
        if py[kind] != ts[kind]:
            failures += 1
            print(f"FAIL: envelope shapes differ for action.kind={kind!r}")
            # A key-level diff first: "present here, absent there" is the
            # omit-rule failure, and it is what a raw JSON diff buries.
            for path, a, b in _diff(py[kind], ts[kind]):
                print(f"  {path}: python={a!r} typescript={b!r}")

    # 2. Both satisfy the published schema.
    try:
        import jsonschema
    except ImportError:
        print("SKIP: jsonschema not installed — schema validation not run")
    else:
        schema = json.loads((REPO / "schemas" / "event.schema.json").read_text())
        validator = jsonschema.Draft202012Validator(schema)
        for lang, shapes in (("python", py), ("typescript", ts)):
            for kind, ev in sorted(shapes.items()):
                # The normalized shapes keep every structural field; only volatile
                # values were replaced, and the schema constrains structure.
                for err in validator.iter_errors(_denormalize(ev)):
                    failures += 1
                    print(f"FAIL: {lang} {kind} violates event.schema.json "
                          f"at {list(err.path)}: {err.message}")

    if failures:
        print(f"\n{failures} envelope-parity failure(s).")
        return 1
    kinds = ", ".join(sorted(py))
    print(f"ok - python and typescript compose identical envelopes for: {kinds}")
    print("ok - both satisfy schemas/event.schema.json")
    return 0


_SENTINEL_DIGESTS = {
    "cid", "intent_digest", "args_digest", "reasoning_digest",
    "model_output_digest", "question_digest", "rationale_digest",
    "reason_digest", "options_digest", "event_id_root",
}


def _denormalize(value, key=None):
    """Put schema-shaped placeholders back where normalization erased them.

    The shape emitters replace volatile values with `<field>` markers so the two
    languages can be diffed. Those markers are not valid digest strings or
    base64url, so schema validation needs a value of the right *form* — the
    schema constrains form, and that is what is being checked here.
    """
    if isinstance(value, str) and value.startswith("<") and value.endswith(">"):
        if key in _SENTINEL_DIGESTS:
            return "sha256:" + "00" * 32
        if key == "ts":
            return "2026-01-01T00:00:00.000Z"
        if key == "latency_ms":
            return 0
        return "x"
    if isinstance(value, dict):
        return {k: _denormalize(v, k) for k, v in value.items()}
    if isinstance(value, list):
        return [_denormalize(v) for v in value]
    return value


def _diff(a, b, path=""):
    """Yield (path, python_value, typescript_value) for every leaf that differs.

    Reports a missing key as the string `<absent>` rather than skipping it: the
    whole point of [TAP-EVT-OMIT] is that absent and null are different, so a
    diff that cannot say which one it saw is useless here.
    """
    if isinstance(a, dict) and isinstance(b, dict):
        for k in sorted(set(a) | set(b)):
            sub = f"{path}.{k}" if path else k
            if k not in a:
                yield sub, "<absent>", b[k]
            elif k not in b:
                yield sub, a[k], "<absent>"
            else:
                yield from _diff(a[k], b[k], sub)
    elif isinstance(a, list) and isinstance(b, list) and len(a) == len(b):
        for i, (x, y) in enumerate(zip(a, b)):
            yield from _diff(x, y, f"{path}[{i}]")
    elif a != b:
        yield path or "<root>", a, b


if __name__ == "__main__":
    sys.exit(main())
